services:
  # Angular Frontend service
  procurement-frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: procurement_frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - procurement_observability
      - postgres_network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

networks:
  procurement_observability:
    external: true
  postgres_network:
    external: true
