// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProcurementAPI.Data;

#nullable disable

namespace ProcurementAPI.Migrations
{
    [DbContext(typeof(ProcurementDbContext))]
    partial class ProcurementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProcurementAPI.Models.Chat.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Messages")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("chat_sessions");
                });

            modelBuilder.Entity("ProcurementAPI.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_code");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("integer")
                        .HasColumnName("lead_time_days");

                    b.Property<int>("MinOrderQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("min_order_quantity");

                    b.Property<decimal?>("StandardCost")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("standard_cost");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit_of_measure");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.ToTable("items");
                });

            modelBuilder.Entity("ProcurementAPI.Models.ItemSpecification", b =>
                {
                    b.Property<int>("SpecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("spec_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpecId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<string>("SpecName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("spec_name");

                    b.Property<string>("SpecValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spec_value");

                    b.HasKey("SpecId");

                    b.HasIndex("ItemId", "SpecName", "SpecValue")
                        .IsUnique();

                    b.ToTable("item_specifications");
                });

            modelBuilder.Entity("ProcurementAPI.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("PoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("po_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PoId"));

                    b.Property<string>("BillingAddress")
                        .HasColumnType("text")
                        .HasColumnName("billing_address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly?>("ExpectedDeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_delivery_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("payment_terms");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("po_number");

                    b.Property<int?>("RfqId")
                        .HasColumnType("integer")
                        .HasColumnName("rfq_id");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("text")
                        .HasColumnName("shipping_address");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PoId");

                    b.HasIndex("PoNumber")
                        .IsUnique();

                    b.HasIndex("RfqId");

                    b.HasIndex("SupplierId");

                    b.ToTable("purchase_orders");
                });

            modelBuilder.Entity("ProcurementAPI.Models.PurchaseOrderLine", b =>
                {
                    b.Property<int>("PoLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("po_line_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PoLineId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<int>("PoId")
                        .HasColumnType("integer")
                        .HasColumnName("po_id");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_ordered");

                    b.Property<int?>("QuoteId")
                        .HasColumnType("integer")
                        .HasColumnName("quote_id");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_price");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PoLineId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PoId");

                    b.HasIndex("QuoteId");

                    b.ToTable("purchase_order_lines");
                });

            modelBuilder.Entity("ProcurementAPI.Models.Quote", b =>
                {
                    b.Property<int>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("quote_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuoteId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_date");

                    b.Property<int>("LineItemId")
                        .HasColumnType("integer")
                        .HasColumnName("line_item_id");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("payment_terms");

                    b.Property<int>("QuantityOffered")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_offered");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("quote_number");

                    b.Property<int>("RfqId")
                        .HasColumnType("integer")
                        .HasColumnName("rfq_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_date");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id");

                    b.Property<string>("TechnicalComplianceNotes")
                        .HasColumnType("text")
                        .HasColumnName("technical_compliance_notes");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_price");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("ValidUntilDate")
                        .HasColumnType("date")
                        .HasColumnName("valid_until_date");

                    b.Property<int?>("WarrantyPeriodMonths")
                        .HasColumnType("integer")
                        .HasColumnName("warranty_period_months");

                    b.HasKey("QuoteId");

                    b.HasIndex("LineItemId");

                    b.HasIndex("RfqId");

                    b.HasIndex("SupplierId");

                    b.ToTable("quotes");
                });

            modelBuilder.Entity("ProcurementAPI.Models.RequestForQuote", b =>
                {
                    b.Property<int>("RfqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rfq_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RfqId"));

                    b.Property<DateOnly?>("AwardDate")
                        .HasColumnType("date")
                        .HasColumnName("award_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("RfqNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rfq_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TermsAndConditions")
                        .HasColumnType("text")
                        .HasColumnName("terms_and_conditions");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<decimal?>("TotalEstimatedValue")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("total_estimated_value");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("RfqId");

                    b.HasIndex("RfqNumber")
                        .IsUnique();

                    b.ToTable("request_for_quotes");
                });

            modelBuilder.Entity("ProcurementAPI.Models.RfqLineItem", b =>
                {
                    b.Property<int>("LineItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("line_item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LineItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("EstimatedUnitCost")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("estimated_unit_cost");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<int>("QuantityRequired")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_required");

                    b.Property<int>("RfqId")
                        .HasColumnType("integer")
                        .HasColumnName("rfq_id");

                    b.Property<string>("TechnicalSpecifications")
                        .HasColumnType("text")
                        .HasColumnName("technical_specifications");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit_of_measure");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("LineItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("RfqId");

                    b.ToTable("rfq_line_items");
                });

            modelBuilder.Entity("ProcurementAPI.Models.RfqSupplier", b =>
                {
                    b.Property<int>("RfqId")
                        .HasColumnType("integer")
                        .HasColumnName("rfq_id");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime>("InvitedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_date");

                    b.Property<bool>("IsResponded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_responded");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("response_date");

                    b.HasKey("RfqId", "SupplierId");

                    b.HasIndex("SupplierId");

                    b.ToTable("rfq_suppliers");
                });

            modelBuilder.Entity("ProcurementAPI.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_name");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("credit_limit");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("payment_terms");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("supplier_code");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("SupplierId");

                    b.HasIndex("SupplierCode")
                        .IsUnique();

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("ProcurementAPI.Models.SupplierCapability", b =>
                {
                    b.Property<int>("CapabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("capability_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CapabilityId"));

                    b.Property<string>("CapabilityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("capability_type");

                    b.Property<string>("CapabilityValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("capability_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id");

                    b.HasKey("CapabilityId");

                    b.HasIndex("SupplierId", "CapabilityType", "CapabilityValue")
                        .IsUnique();

                    b.ToTable("supplier_capabilities");
                });

            modelBuilder.Entity("ProcurementAPI.Models.SupplierPerformance", b =>
                {
                    b.Property<decimal?>("AvgQuotePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_quote_price");

                    b.Property<int>("AwardedQuotes")
                        .HasColumnType("integer")
                        .HasColumnName("awarded_quotes");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id");

                    b.Property<decimal?>("TotalPoValue")
                        .HasColumnType("numeric")
                        .HasColumnName("total_po_value");

                    b.Property<int>("TotalPurchaseOrders")
                        .HasColumnType("integer")
                        .HasColumnName("total_purchase_orders");

                    b.Property<int>("TotalQuotes")
                        .HasColumnType("integer")
                        .HasColumnName("total_quotes");

                    b.ToTable((string)null);

                    b.ToView("supplier_performance", (string)null);
                });

            modelBuilder.Entity("ProcurementAPI.Models.ItemSpecification", b =>
                {
                    b.HasOne("ProcurementAPI.Models.Item", "Item")
                        .WithMany("ItemSpecifications")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ProcurementAPI.Models.PurchaseOrder", b =>
                {
                    b.HasOne("ProcurementAPI.Models.RequestForQuote", "RequestForQuote")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("RfqId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProcurementAPI.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RequestForQuote");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ProcurementAPI.Models.PurchaseOrderLine", b =>
                {
                    b.HasOne("ProcurementAPI.Models.Item", "Item")
                        .WithMany("PurchaseOrderLines")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcurementAPI.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderLines")
                        .HasForeignKey("PoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcurementAPI.Models.Quote", "Quote")
                        .WithMany("PurchaseOrderLines")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Item");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("ProcurementAPI.Models.Quote", b =>
                {
                    b.HasOne("ProcurementAPI.Models.RfqLineItem", "RfqLineItem")
                        .WithMany("Quotes")
                        .HasForeignKey("LineItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcurementAPI.Models.RequestForQuote", "RequestForQuote")
                        .WithMany("Quotes")
                        .HasForeignKey("RfqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcurementAPI.Models.Supplier", "Supplier")
                        .WithMany("Quotes")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestForQuote");

                    b.Navigation("RfqLineItem");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ProcurementAPI.Models.RfqLineItem", b =>
                {
                    b.HasOne("ProcurementAPI.Models.Item", "Item")
                        .WithMany("RfqLineItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProcurementAPI.Models.RequestForQuote", "RequestForQuote")
                        .WithMany("RfqLineItems")
                        .HasForeignKey("RfqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("RequestForQuote");
                });

            modelBuilder.Entity("ProcurementAPI.Models.RfqSupplier", b =>
                {
                    b.HasOne("ProcurementAPI.Models.RequestForQuote", "RequestForQuote")
                        .WithMany("RfqSuppliers")
                        .HasForeignKey("RfqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcurementAPI.Models.Supplier", "Supplier")
                        .WithMany("RfqSuppliers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestForQuote");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ProcurementAPI.Models.SupplierCapability", b =>
                {
                    b.HasOne("ProcurementAPI.Models.Supplier", "Supplier")
                        .WithMany("SupplierCapabilities")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ProcurementAPI.Models.Item", b =>
                {
                    b.Navigation("ItemSpecifications");

                    b.Navigation("PurchaseOrderLines");

                    b.Navigation("RfqLineItems");
                });

            modelBuilder.Entity("ProcurementAPI.Models.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderLines");
                });

            modelBuilder.Entity("ProcurementAPI.Models.Quote", b =>
                {
                    b.Navigation("PurchaseOrderLines");
                });

            modelBuilder.Entity("ProcurementAPI.Models.RequestForQuote", b =>
                {
                    b.Navigation("PurchaseOrders");

                    b.Navigation("Quotes");

                    b.Navigation("RfqLineItems");

                    b.Navigation("RfqSuppliers");
                });

            modelBuilder.Entity("ProcurementAPI.Models.RfqLineItem", b =>
                {
                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("ProcurementAPI.Models.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");

                    b.Navigation("Quotes");

                    b.Navigation("RfqSuppliers");

                    b.Navigation("SupplierCapabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
